services:
  - type: web
    name: simpro-catalogue-manager
    runtime: python
    buildCommand: bash build.sh
    startCommand: python3 run.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
